#Config file for agent definitions


ag1:
  agent_cls: Agent
  params:
    load_id: ag1
    pv_id: PV1
  data_info:
    data_file: 'dataset_gecad_clean.csv'
    data_proc_cls: GecadDataProcessor
  tariffs:
    tar_type: 'double_rate'
    double_rate_params:
      empty_start: 9
      empty_end: 20
      empty_val: 0.1
      no_empty_val: 0.1
  battery:
    capacity: 20  
    charging_power_limit: 5.0
    discharging_power_limit: -5.0
    charging_efficiency: 0.9
    discharging_efficiency: 0.9
    initial_soc_percent: 0.75

ag2:
  agent_cls: Agent
  params:
    load_id: ag2
    pv_id: PV2
  data_info:
    data_file: 'dataset_gecad_clean.csv'
    data_proc_cls: GecadDataProcessor
  tariffs:
    tar_type: 'double_rate'
    double_rate_params:
      empty_start: 9
      empty_end: 20
      empty_val: 0.1
      no_empty_val: 0.1
  battery:
    capacity: 20  
    charging_power_limit: 5.0
    discharging_power_limit: -5.0
    charging_efficiency: 0.9
    discharging_efficiency: 0.9
    initial_soc_percent: 0.75